# RICEZIONE DATI
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

# INOLTRO A KAFKA
<match social_stream.**>
  @type kafka2

  brokers kafka:29092
  default_topic raw-tech-stream

  <format>
    @type json
  </format>

  <buffer>
    @type file
    path /tmp/fluentd-buffers/kafka.buffer
    flush_interval 3s
  </buffer>
</match>